/* tslint:disable */
/* eslint-disable */
/**
 * Weather-Cam-API (OpenAPI 3.0)
 * Weather-Cam-API is a REST API created as a part a software project at Eötvös Loránd university. The goal of the project is to turn old/unused mobile phones and an [esp8266](https://www.espressif.com/en/products/socs/esp8266) into a diy weather stations capable of recording photos, temperature, pressure and humidity data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * StorageInfo contains data about the storage usage of the server.
 * @export
 * @interface StorageInfo
 */
export interface StorageInfo {
    /**
     * total_storage is the total amount of storage in bytes.
     * @type {number}
     * @memberof StorageInfo
     */
    totalStorage: number;
    /**
     * used_storage is the amount of used storage in bytes.
     * @type {number}
     * @memberof StorageInfo
     */
    usedStorage: number;
}

/**
 * Check if a given object implements the StorageInfo interface.
 */
export function instanceOfStorageInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalStorage" in value;
    isInstance = isInstance && "usedStorage" in value;

    return isInstance;
}

export function StorageInfoFromJSON(json: any): StorageInfo {
    return StorageInfoFromJSONTyped(json, false);
}

export function StorageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalStorage': json['total_storage'],
        'usedStorage': json['used_storage'],
    };
}

export function StorageInfoToJSON(value?: StorageInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total_storage': value.totalStorage,
        'used_storage': value.usedStorage,
    };
}

