/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.weatherapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * ApiResponse contains information about the result of a request.
 *
 * @param code code is the status of the returned request. code follows the [HTTP response codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)
 * @param type type is used to categorize responses. The different types of responses can be found [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status).
 * @param message message is a more detailed information about the response.
 */
@Serializable

data class ApiResponseEntity (

    /* code is the status of the returned request. code follows the [HTTP response codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) */
    @SerialName(value = "code")
    val code: kotlin.Int,

    /* type is used to categorize responses. The different types of responses can be found [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status). */
    @SerialName(value = "type")
    val type: kotlin.String,

    /* message is a more detailed information about the response. */
    @SerialName(value = "message")
    val message: kotlin.String

)

