/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.weatherapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param measurementId measurement_id is a __unique__ identifier for measurements.   measurement_id is an unsigned integer. 
 * @param stationId station_id is a __unique__ identifier for weather stations.   station_id is an unsigned integer. 
 */
@Serializable

data class IndexedMeasurementAllOfEntity (

    /* measurement_id is a __unique__ identifier for measurements.   measurement_id is an unsigned integer.  */
    @SerialName(value = "measurement_id")
    val measurementId: kotlin.Long? = null,

    /* station_id is a __unique__ identifier for weather stations.   station_id is an unsigned integer.  */
    @SerialName(value = "station_id")
    val stationId: kotlin.Long? = null

)

