/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.weatherapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * IndexedMeasurement is the same as Measurement with the exception of added properties station_id and measurement_id.   station_id and measurement_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard. 
 *
 * @param temperature temperature in celsius.
 * @param pressure pressure in millibars.
 * @param humidity humidity in percentage.
 * @param battery remaining battery in percentage
 * @param timestamp the time of recording the measurement timestamp follows the [unix time](https://en.wikipedia.org/wiki/Unix_time) standard. 
 * @param measurementId measurement_id is a __unique__ identifier for measurements.   measurement_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard. 
 * @param stationId station_id is a __unique__ identifier for weather stations.   station_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard. 
 */
@Serializable

data class IndexedMeasurementEntity (

    /* temperature in celsius. */
    @SerialName(value = "temperature")
    val temperature: kotlin.Float? = null,

    /* pressure in millibars. */
    @SerialName(value = "pressure")
    val pressure: kotlin.Float? = null,

    /* humidity in percentage. */
    @SerialName(value = "humidity")
    val humidity: kotlin.Float? = null,

    /* remaining battery in percentage */
    @SerialName(value = "battery")
    val battery: kotlin.Float? = null,

    /* the time of recording the measurement timestamp follows the [unix time](https://en.wikipedia.org/wiki/Unix_time) standard.  */
    @SerialName(value = "timestamp")
    val timestamp: kotlin.Long? = null,

    /* measurement_id is a __unique__ identifier for measurements.   measurement_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard.  */
    @Contextual @SerialName(value = "measurement_id")
    val measurementId: java.util.UUID? = null,

    /* station_id is a __unique__ identifier for weather stations.   station_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard.  */
    @Contextual @SerialName(value = "station_id")
    val stationId: java.util.UUID? = null

)

