/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.weatherapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Measurement contains the data recorded by the sensors.
 *
 * @param temperature temperature in celsius.
 * @param pressure pressure in millibars.
 * @param humidity humidity in percentage.
 * @param battery remaining battery in percentage
 * @param timestamp the time of recording the measurement timestamp follows the [unix time](https://en.wikipedia.org/wiki/Unix_time) standard. 
 */
@Serializable

data class MeasurementEntity (

    /* temperature in celsius. */
    @SerialName(value = "temperature")
    val temperature: kotlin.Float,

    /* pressure in millibars. */
    @SerialName(value = "pressure")
    val pressure: kotlin.Float,

    /* humidity in percentage. */
    @SerialName(value = "humidity")
    val humidity: kotlin.Float,

    /* remaining battery in percentage */
    @SerialName(value = "battery")
    val battery: kotlin.Float,

    /* the time of recording the measurement timestamp follows the [unix time](https://en.wikipedia.org/wiki/Unix_time) standard.  */
    @SerialName(value = "timestamp")
    val timestamp: kotlin.Long

)

