/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.weatherapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * StationApiKey contains information about the newly added station and it's api_key.   **Important**: The api_key is only recieved once after creating a new station make sure to write it down somewhere!  
 *
 * @param stationId station_id is a __unique__ identifier for stations.  station_id is an unsigned integer. 
 * @param apiKey api_key gives access to upload measurements to the server.   
 */
@Serializable

data class StationApiKeyEntity (

    /* station_id is a __unique__ identifier for stations.  station_id is an unsigned integer.  */
    @SerialName(value = "station_id")
    val stationId: kotlin.Long,

    /* api_key gives access to upload measurements to the server.    */
    @SerialName(value = "api_key")
    val apiKey: kotlin.String

)

