/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.weatherapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Station contains information about a weather station.
 *
 * @param stationId station_id is a __unique__ identifier for stations.  station_id is an unsigned integer. 
 * @param stationName station_name is the unique name of the station.
 */
@Serializable

data class StationEntity (

    /* station_id is a __unique__ identifier for stations.  station_id is an unsigned integer.  */
    @SerialName(value = "station_id")
    val stationId: kotlin.Long,

    /* station_name is the unique name of the station. */
    @SerialName(value = "station_name")
    val stationName: kotlin.String

)

