/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.weatherapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * StorageInfo contains data about the storage usage of the server.
 *
 * @param totalStorage total_storage is the total amount of storage in bytes.
 * @param usedStorage used_storage is the amount of used storage in bytes.
 */
@Serializable

data class StorageInfoEntity (

    /* total_storage is the total amount of storage in bytes. */
    @SerialName(value = "total_storage")
    val totalStorage: kotlin.Long,

    /* used_storage is the amount of used storage in bytes. */
    @SerialName(value = "used_storage")
    val usedStorage: kotlin.Long

)

