/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.weatherapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * User contains all the user information.
 *
 * @param userId user_id is the unique identifier of the user. station_id is an unsigned integer. 
 * @param username username is a unique name used to identify the user.
 * @param password 
 */
@Serializable

data class UserEntity (

    /* user_id is the unique identifier of the user. station_id is an unsigned integer.  */
    @SerialName(value = "user_id")
    val userId: kotlin.Long,

    /* username is a unique name used to identify the user. */
    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "password")
    val password: kotlin.String

)

