/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.weatherapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * User contains all the user information.
 *
 * @param username username is a unique name used to identify the user.
 * @param password 
 */
@Serializable

data class UserUpdateableEntity (

    /* username is a unique name used to identify the user. */
    @SerialName(value = "username")
    val username: kotlin.String? = null,

    @SerialName(value = "password")
    val password: kotlin.String? = null

)

