/* tslint:disable */
/* eslint-disable */
/**
 * Weather-Cam-API (OpenAPI 3.0)
 * Weather-Cam-API is a REST API created as a part a software project at Eötvös Loránd university. The goal of the project is to turn old/unused mobile phones and an [esp8266](https://www.espressif.com/en/products/socs/esp8266) into a diy weather stations capable of recording photos, temperature, pressure and humidity data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndexedMeasurementAllOf
 */
export interface IndexedMeasurementAllOf {
    /**
     * measurement_id is a __unique__ identifier for measurements.  
measurement_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard.

     * @type {string}
     * @memberof IndexedMeasurementAllOf
     */
    measurementId?: string;
    /**
     * station_id is a __unique__ identifier for weather stations.  
station_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard.

     * @type {string}
     * @memberof IndexedMeasurementAllOf
     */
    stationId?: string;
}

/**
 * Check if a given object implements the IndexedMeasurementAllOf interface.
 */
export function instanceOfIndexedMeasurementAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IndexedMeasurementAllOfFromJSON(json: any): IndexedMeasurementAllOf {
    return IndexedMeasurementAllOfFromJSONTyped(json, false);
}

export function IndexedMeasurementAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexedMeasurementAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'measurementId': !exists(json, 'measurement_id') ? undefined : json['measurement_id'],
        'stationId': !exists(json, 'station_id') ? undefined : json['station_id'],
    };
}

export function IndexedMeasurementAllOfToJSON(value?: IndexedMeasurementAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'measurement_id': value.measurementId,
        'station_id': value.stationId,
    };
}

