/* tslint:disable */
/* eslint-disable */
/**
 * Weather-Cam-API (OpenAPI 3.0)
 * Weather-Cam-API is a REST API created as a part a software project at Eötvös Loránd university. The goal of the project is to turn old/unused mobile phones and an [esp8266](https://www.espressif.com/en/products/socs/esp8266) into a diy weather stations capable of recording photos, temperature, pressure and humidity data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * User contains all the user information.
 * @export
 * @interface UserUpdateable
 */
export interface UserUpdateable {
    /**
     * username is a unique name used to identify the user.
     * @type {string}
     * @memberof UserUpdateable
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateable
     */
    password?: string;
}

/**
 * Check if a given object implements the UserUpdateable interface.
 */
export function instanceOfUserUpdateable(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserUpdateableFromJSON(json: any): UserUpdateable {
    return UserUpdateableFromJSONTyped(json, false);
}

export function UserUpdateableFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function UserUpdateableToJSON(value?: UserUpdateable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

