/**
 * Weather-Cam-API (OpenAPI 3.0)
 *
 * Weather-Cam-API is a REST API created as a part a software project at Eötvös Loránd university. The goal of the project is to turn old/unused mobile phones and an [esp8266](https://www.espressif.com/en/products/socs/esp8266) into a diy weather stations capable of recording photos, temperature, pressure and humidity data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.libapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * IndexedMeasurement is the same as Measurement with the exception of added properties station_id and measurement_id.   station_id and measurement_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard. 
 *
 * @param temperature temperature in celsius.
 * @param pressure pressure in millibars.
 * @param humidity humidity in percentage.
 * @param measurementId measurement_id is a __unique__ identifier for measurements.   measurement_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard. 
 * @param stationId station_id is a __unique__ identifier for weather stations.   station_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard. 
 */
@Serializable
data class IndexedMeasurementEntity (

    /* temperature in celsius. */
    @SerialName(value = "temperature")
    val temperature: kotlin.Float? = null,

    /* pressure in millibars. */
    @SerialName(value = "pressure")
    val pressure: kotlin.Float? = null,

    /* humidity in percentage. */
    @SerialName(value = "humidity")
    val humidity: kotlin.Float? = null,

    /* measurement_id is a __unique__ identifier for measurements.   measurement_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard.  */
    @Contextual @SerialName(value = "measurement_id")
    val measurementId: java.util.UUID? = null,

    /* station_id is a __unique__ identifier for weather stations.   station_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard.  */
    @Contextual @SerialName(value = "station_id")
    val stationId: java.util.UUID? = null

)

