/**
 * Weather-Cam-API (OpenAPI 3.0)
 *
 * Weather-Cam-API is a REST API created as a part a software project at Eötvös Loránd university. The goal of the project is to turn old/unused mobile phones and an [esp8266](https://www.espressif.com/en/products/socs/esp8266) into a diy weather stations capable of recording photos, temperature, pressure and humidity data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.libapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Measurement contains the data recorded by the sensors.
 *
 * @param temperature temperature in celsius.
 * @param pressure pressure in millibars.
 * @param humidity humidity in percentage.
 */
@Serializable
data class MeasurementEntity (

    /* temperature in celsius. */
    @SerialName(value = "temperature")
    val temperature: kotlin.Float? = null,

    /* pressure in millibars. */
    @SerialName(value = "pressure")
    val pressure: kotlin.Float? = null,

    /* humidity in percentage. */
    @SerialName(value = "humidity")
    val humidity: kotlin.Float? = null

)

