/**
 * Weather-Cam-API (OpenAPI 3.0)
 *
 * Weather-Cam-API is a REST API created as a part a software project at Eötvös Loránd university. The goal of the project is to turn old/unused mobile phones and an [esp8266](https://www.espressif.com/en/products/socs/esp8266) into a diy weather stations capable of recording photos, temperature, pressure and humidity data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.libapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * StorageInfo contains data about the storage usage of the server.
 *
 * @param totalStorage total_storage is the total amount of storage in bytes.
 * @param usedStorage total_storage is the amount of free storage in bytes.
 */
@Serializable
data class StorageInfoEntity (

    /* total_storage is the total amount of storage in bytes. */
    @SerialName(value = "total_storage")
    val totalStorage: kotlin.Long? = null,

    /* total_storage is the amount of free storage in bytes. */
    @SerialName(value = "used_storage")
    val usedStorage: kotlin.Long? = null

)

