/**
 * Weather-Cam-API (OpenAPI 3.0)
 *
 * Weather-Cam-API is a REST API created as a part a software project at Eötvös Loránd university. The goal of the project is to turn old/unused mobile phones and an [esp8266](https://www.espressif.com/en/products/socs/esp8266) into a diy weather stations capable of recording photos, temperature, pressure and humidity data. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.libapi.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * User contains all the user information.
 *
 * @param userId user_id is the unique identifier of the user. station_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard. 
 * @param username username is a unique name used to identify the user.
 * @param password 
 */
@Serializable
data class UserEntity (

    /* user_id is the unique identifier of the user. station_id follows the [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) standard.  */
    @Contextual @SerialName(value = "user_id")
    val userId: java.util.UUID? = null,

    /* username is a unique name used to identify the user. */
    @SerialName(value = "username")
    val username: kotlin.String? = null,

    @SerialName(value = "password")
    val password: kotlin.String? = null

)

